# Generated by Django 5.0.6 on 2024-05-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_coupon_description_coupon_store_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.TextField(blank=True, help_text='tags, separated with coma. eg: "clothes,leggings,pants,shorts"', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, help_text="Store doesn't exist? Create new Store first", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shop.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, help_text="Don't fill, will be slugified", max_length=100, unique=True),
        ),
    ]
