# Generated by Django 5.0.6 on 2024-05-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='shop.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
